CREATE TABLE customer (
                          customer_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name varchar(100) NOT NULL,
                          email varchar(100) NOT NULL,
                          mobile_number varchar(20) NOT NULL,
                         house_affiliation varchar(50) NOT NULL,
                          pwd varchar(500) NOT NULL,
                          role varchar(100) NOT NULL,
                          create_dt date DEFAULT NULL
);

CREATE TABLE accounts (
                          customer_id int NOT NULL,
                          account_number int NOT NULL,
                          account_type varchar(100) NOT NULL,
                          branch_address varchar(200) NOT NULL ,
                          create_dt date DEFAULT NULL,
                          PRIMARY KEY(account_number),
                          CONSTRAINT customer_ibfk_1 FOREIGN KEY (customer_id) REFERENCES customer(customer_id) ON DELETE CASCADE
);


CREATE TABLE account_transactions (
                                      transaction_id varchar(200) NOT NULL,
                                      account_number int NOT NULL,
                                      customer_id int NOT NULL,
                                      transaction_dt date NOT NULL,
                                      transaction_summary varchar(200) NOT NULL,
                                      transaction_type varchar(100) NOT NULL,
                                      transaction_amt int NOT NULL,
                                      closing_balance int NOT NULL,
                                      create_dt date DEFAULT NULL,
                                      PRIMARY KEY (transaction_id),
                                      CONSTRAINT accounts_ibfk_2 FOREIGN KEY (account_number) REFERENCES accounts (account_number) ON DELETE CASCADE,
                                      CONSTRAINT acct_user_ibfk_1 FOREIGN KEY (customer_id) REFERENCES customer (customer_id) ON DELETE CASCADE
);

CREATE TABLE loan (
                      loan_number int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      customer_id int NOT NULL,
                      start_dt date NOT NULL,
                      loan_type varchar(100) NOT NULL,
                      total_loan int NOT NULL,
                      amount_paid int NOT NULL,
                      outstanding_amount int NOT NULL,
                      create_dt date DEFAULT NULL,
                      CONSTRAINT loan_customer_ibfk_1 FOREIGN KEY (customer_id) REFERENCES customer(customer_id) ON DELETE CASCADE
);


CREATE TABLE card (
                      card_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                      card_number varchar(100) NOT NULL,
                      customer_id int NOT NULL,
                      card_type varchar(100) NOT NULL,
                      total_limit int NOT NULL,
                      amount_used int NOT NULL,
                      available_amount int NOT NULL,
                      create_dt date DEFAULT NULL,
                      PRIMARY KEY (card_id),
                      CONSTRAINT card_customer_ibfk_1 FOREIGN KEY (customer_id) REFERENCES customer(customer_id) ON DELETE CASCADE
);


CREATE TABLE notice_details (
                                notice_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                notice_summary varchar(200) NOT NULL,
                                notice_details varchar(500) NOT NULL,
                                notice_beg_dt date NOT NULL,
                                notice_end_dt date NOT NULL,
                                create_dt date DEFAULT NULL,
                                update_dt date DEFAULT NULL,
                                PRIMARY KEY (notice_id)
);


INSERT INTO customer (name, email, mobile_number, pwd, role, create_dt)
VALUES ('Happy', 'happy@example.com', '5334122365', '$2a$12$88.f6upbBvy0okEa7OfHFuorV29qeK.sVbB9VQ6J6dWM1bW6Qef8m', 'admin', CURRENT_DATE);

INSERT INTO accounts (customer_id, account_number, account_type, branch_address, create_dt)
VALUES (1, 1865764534, 'Savings', '123 Main Street, New York', CURRENT_DATE);

INSERT INTO account_transactions (transaction_id, account_number, customer_id, transaction_dt, transaction_summary, transaction_type, transaction_amt,
                                  closing_balance, create_dt)
VALUES (gen_random_uuid(), 1865764534, 1, CURRENT_DATE - INTERVAL '7 days', 'Coffee Shop', 'Debited', 30, 34500, CURRENT_DATE - INTERVAL '7 days');

INSERT INTO account_transactions (transaction_id, account_number, customer_id, transaction_dt, transaction_summary, transaction_type, transaction_amt,
                                  closing_balance, create_dt)
VALUES (gen_random_uuid(), 1865764534, 1, CURRENT_DATE - INTERVAL '6 days', 'Uber', 'Debited', 100, 34400, CURRENT_DATE - INTERVAL '6 days');

INSERT INTO account_transactions (transaction_id, account_number, customer_id, transaction_dt, transaction_summary, transaction_type, transaction_amt,
                                  closing_balance, create_dt)
VALUES (gen_random_uuid(), 1865764534, 1, CURRENT_DATE - INTERVAL '5 days', 'Credit', 'Credited', 500, 34900, CURRENT_DATE - INTERVAL '5 days');

INSERT INTO account_transactions (transaction_id, account_number, customer_id, transaction_dt, transaction_summary, transaction_type, transaction_amt,
                                  closing_balance, create_dt)
VALUES (gen_random_uuid(), 1865764534, 1, CURRENT_DATE - INTERVAL '4 days', 'Ebay', 'Debited', 600, 34300, CURRENT_DATE - INTERVAL '4 days');

INSERT INTO account_transactions (transaction_id, account_number, customer_id, transaction_dt, transaction_summary, transaction_type, transaction_amt,
                                  closing_balance, create_dt)
VALUES (gen_random_uuid(), 1865764534, 1, CURRENT_DATE - INTERVAL '2 days', 'OnlineTransfer', 'Credited', 700, 35000, CURRENT_DATE - INTERVAL '2 days');

INSERT INTO account_transactions (transaction_id, account_number, customer_id, transaction_dt, transaction_summary, transaction_type, transaction_amt,
                                  closing_balance, create_dt)
VALUES (gen_random_uuid(), 1865764534, 1, CURRENT_DATE - INTERVAL '1 days', 'Amazon.com', 'Debited', 100, 34900, CURRENT_DATE - INTERVAL '1 days');

INSERT INTO loan (customer_id, start_dt, loan_type, total_loan, amount_paid, outstanding_amount, create_dt)
VALUES (1, '2020-10-13', 'Home', 200000, 50000, 150000, '2020-10-13');

INSERT INTO loan (customer_id, start_dt, loan_type, total_loan, amount_paid, outstanding_amount, create_dt)
VALUES (1, '2020-06-06', 'Vehicle', 40000, 10000, 30000, '2020-06-06');

INSERT INTO loan (customer_id, start_dt, loan_type, total_loan, amount_paid, outstanding_amount, create_dt)
VALUES (1, '2018-02-14', 'Home', 50000, 10000, 40000, '2018-02-14');

INSERT INTO loan (customer_id, start_dt, loan_type, total_loan, amount_paid, outstanding_amount, create_dt)
VALUES (1, '2018-02-14', 'Personal', 10000, 3500, 6500, '2018-02-14');

INSERT INTO card (card_number, customer_id, card_type, total_limit, amount_used, available_amount, create_dt)
VALUES ('4565XXXX4656', 1, 'Credit', 10000, 500, 9500, CURRENT_DATE);

INSERT INTO card (card_number, customer_id, card_type, total_limit, amount_used, available_amount, create_dt)
VALUES ('3455XXXX8673', 1, 'Credit', 7500, 600, 6900, CURRENT_DATE);

INSERT INTO card (card_number, customer_id, card_type, total_limit, amount_used, available_amount, create_dt)
VALUES ('2359XXXX9346', 1, 'Credit', 20000, 4000, 16000, CURRENT_DATE);

INSERT INTO notice_details (notice_summary, notice_details, notice_beg_dt, notice_end_dt, create_dt, update_dt)
VALUES ('Home Loan Interest rates reduced', 'Home loan interest rates are reduced as per the government guidelines. The updated rates will be effective immediately',
        CURRENT_DATE - INTERVAL '30 days', CURRENT_DATE + INTERVAL '30 days', CURRENT_DATE, NULL);

INSERT INTO notice_details (notice_summary, notice_details, notice_beg_dt, notice_end_dt, create_dt, update_dt)
VALUES ('Net Banking Offers', 'Customers who will opt for Internet banking while opening a saving account will get a $50 amazon voucher',
        CURRENT_DATE - INTERVAL '30 days', CURRENT_DATE + INTERVAL '30 days', CURRENT_DATE, NULL);

INSERT INTO notice_details (notice_summary, notice_details, notice_beg_dt, notice_end_dt, create_dt, update_dt)
VALUES ('Mobile App Downtime', 'The mobile application of the StarkSavingsBank will be down from 2AM-5AM on 12/05/2020 due to maintenance activities',
        CURRENT_DATE - INTERVAL '30 days', CURRENT_DATE + INTERVAL '30 days', CURRENT_DATE, NULL);

INSERT INTO notice_details (notice_summary, notice_details, notice_beg_dt, notice_end_dt, create_dt, update_dt)
VALUES ('E Auction notice', 'There will be an e-auction on 12/08/2020 on the Bank website for all the stubborn arrears. Interested parties can participate in the e-auction',
        CURRENT_DATE - INTERVAL '30 days', CURRENT_DATE + INTERVAL '30 days', CURRENT_DATE, NULL);

INSERT INTO notice_details (notice_summary, notice_details, notice_beg_dt, notice_end_dt, create_dt, update_dt)
VALUES ('Launch of Millennia card', 'Millennia Credit card are launched for the premium customers of StarkSavingsBank. With these card, you will get 5% cashback for each purchase',
        CURRENT_DATE - INTERVAL '30 days', CURRENT_DATE + INTERVAL '30 days', CURRENT_DATE, NULL);

INSERT INTO notice_details (notice_summary, notice_details, notice_beg_dt, notice_end_dt, create_dt, update_dt)
VALUES ('COVID-19 Insurance', 'StarkSavingsBank launched an insurance policy which will cover COVID-19 expenses. Please reach out to the branch for more details',
        CURRENT_DATE - INTERVAL '30 days', CURRENT_DATE + INTERVAL '30 days', CURRENT_DATE, NULL);


CREATE TABLE contact (
                         contact_id varchar(100) NOT NULL,
                         contact_name varchar(50) NOT NULL,
                         contact_email varchar(100) NOT NULL,
                         house varchar(50) NOT NULL,
                         subject varchar(500) NOT NULL,
                         message varchar(2000) NOT NULL,
                         create_dt date DEFAULT NULL,
                         PRIMARY KEY (contact_id)
);


CREATE TABLE authorities (
                             id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             customer_id int NOT NULL,
                             name varchar(50) NOT NULL,
                             CONSTRAINT authorities_ibfk_1 FOREIGN KEY (customer_id) REFERENCES customer(customer_id)
);



INSERT INTO notice_details (notice_summary, notice_details, issued_date, house_affiliation, notice_beg_dt, notice_end_dt, create_dt)
VALUES
    ('Winter Savings Rates Increased', 'Prepare for winter with our new high-yield savings accounts. The North remembers... to save!', '299 AC, 3rd Moon', 'Stark', '2024-11-01', '2025-01-01', '2024-11-01'),
    ('Golden Dragons Investment Opportunity', 'Exclusive high-risk, high-reward investment options for our most ambitious clients. A Lannister always pays their dividends!', '299 AC, 5th Moon', 'Lannister', '2024-11-01', '2025-01-01', '2024-11-01'),
    ('DragonFlame Insurance Now Available', 'Protect your assets against unforeseen dragon-related incidents. Because when you play with Flame, you might need insurance.', '299 AC, 7th Moon', 'Targaryen', '2024-11-01', '2025-01-01', '2024-11-01'),
    ('Stormlands Stability Fund', 'Weather any financial storm with our new stability fund. Ours is the fury... against market volatility!', '299 AC, 9th Moon', 'Baratheon', '2024-11-01', '2025-01-01', '2024-11-01'),
    ('Iron Bank Policy Update', 'Important changes to our lending policies. The Iron Bank will have its due, but now with more flexible terms!', '299 AC, 11th Moon', 'Other', '2024-11-01', '2025-01-01', '2024-11-01'),
    ('Fur-tastic Home Loan Deals!', 'Wrap yourself in savings this winter! Get cozy with our reduced home loan rates. Remember, the North pays less interest!', '299 AC, 13th Moon', 'Stark', '2024-11-01', '2025-01-01', '2024-11-01'),
    ('Knightly Credit Card Rewards', 'Join our credit card program and earn rewards worthy of a knight! Every swipe brings you closer to glory!', '299 AC, 15th Moon', 'Baratheon', '2024-11-01', '2025-01-01', '2024-11-01'),
    ('Winterfell Financial Workshops', 'Join us for free workshops on budgeting and saving. Learn how to stretch your gold further this winter!', '299 AC, 17th Moon', 'Stark', '2024-11-01', '2025-01-01', '2024-11-01'),
    ('Valyrian Steel Home Insurance!', 'Protect your home with insurance as strong as Valyrian steel. Because a good home is worth fighting for!', '299 AC, 19th Moon', 'Targaryen', '2024-11-01', '2025-01-01', '2024-11-01'),
    ('Ironclad Investment Strategies', 'Turn your gold into a fortune with our new investment strategies. A good plan is like a fortress, it stands strong!', '299 AC, 21st Moon', 'Lannister', '2024-11-01', '2025-01-01', '2024-11-01'),
    ('Stark Loyalty Program Launch', 'Join our Stark Loyalty Program and earn rewards for every gold coin spent! Loyalty is a virtue in Winterfell.', '299 AC, 23rd Moon', 'Stark', '2024-11-01', '2025-01-01', '2024-11-01'),
    ('Mysterious Gold Coin Exchange', 'Join us for a special event to learn about the mysterious gold coin exchange rates. Knowledge is power, and power is wealth!', '299 AC, 25th Moon', 'Other', '2024-11-01', '2025-01-01', '2024-11-01'),
    ('Banking Under the Wall', 'Explore our special accounts designed for those beyond the Wall. Because even the Night Watch needs a good savings plan!', '299 AC, 27th Moon', 'Stark', '2024-11-01', '2025-01-01', '2024-11-01'),
    ('Financing Your Quest for Glory', 'Take out a loan to finance your quest for glory! Just like a hero, your dreams are worth chasing!', '299 AC, 29th Moon', 'Baratheon', '2024-11-01', '2025-01-01', '2024-11-01'),
    ('Protect Your Home with Our Direwolf Insurance', 'Insure your home against direwolf damages! Because even the fiercest need protection.', '299 AC, 31st Moon', 'Stark', '2024-11-01', '2025-01-01', '2024-11-01'),
    ('Rider of the Storm Loans', 'Take advantage of our rider of the storm loans! Fast and reliable funding for your next big idea!', '299 AC, 33rd Moon', 'Baratheon', '2024-11-01', '2025-01-01', '2024-11-01'),
    ('Wealth Beyond the Wall', 'Learn about our new accounts for those daring enough to venture beyond the Wall. Opportunities await!', '299 AC, 35th Moon', 'Stark', '2024-11-01', '2025-01-01', '2024-11-01'),
    ('The Gold Standard Savings Account', 'Discover our new Gold Standard savings account, where your money is as good as gold! Because we all need a little Lannister touch.', '299 AC, 37th Moon', 'Lannister', '2024-11-01', '2025-01-01', '2024-11-01');

INSERT INTO notice_details (notice_summary, notice_details, issued_date, house_affiliation, notice_beg_dt, notice_end_dt, create_dt)
VALUES
    ('Battlefield Budgeting', 'Join our budgeting seminar to learn how to win the financial battle! Every coin counts in the game of savings.', '299 AC, 1st Moon', 'Stark', '2024-11-01', '2025-01-01', '2024-11-01'),
    ('Iron Throne Investment Fair', 'Step into the arena of investments! Our experts will help you seize the Iron Throne of financial success!', '299 AC, 2nd Moon', 'Lannister', '2024-11-01', '2025-01-01', '2024-11-01'),
    ('Targaryen Fire Sale!', 'Unleash your inner dragon! Special discounts on loans that are hotter than dragonfire.', '299 AC, 4th Moon', 'Targaryen', '2024-11-01', '2025-01-01', '2024-11-01'),
    ('Oath of the Savings Account', 'Take the oath! Open a savings account and earn interest worthy of the Night’s Watch.', '299 AC, 6th Moon', 'Stark', '2024-11-01', '2025-01-01', '2024-11-01'),
    ('Lannister Loans Are Here!', 'Borrow wisely! Lannisters are known for their gold, and our loans are no different.', '299 AC, 8th Moon', 'Lannister', '2024-11-01', '2025-01-01', '2024-11-01'),
    ('Directing Your Finances', 'Discover how to direct your finances like a master strategist. Take control of your financial destiny!', '299 AC, 10th Moon', 'Baratheon', '2024-11-01', '2025-01-01', '2024-11-01'),
    ('Wildling Wealth Workshops', 'Calling all Wildlings! Join our wealth management workshops to learn how to protect your gold from the elements.', '299 AC, 12th Moon', 'Other', '2024-11-01', '2025-01-01', '2024-11-01'),
    ('Maesters of Money', 'Meet our Maesters for financial advice! They have all the knowledge to help you prosper.', '299 AC, 14th Moon', 'Targaryen', '2024-11-01', '2025-01-01', '2024-11-01'),
    ('A Shield Against Debt', 'Arm yourself with knowledge to protect against the dangers of debt! Because in this world, a wise man is prepared.', '299 AC, 16th Moon', 'Baratheon', '2024-11-01', '2025-01-01', '2024-11-01'),
    ('Golden Opportunity Account', 'Open an account with golden opportunities that shine brighter than the sun over King’s Landing.', '299 AC, 18th Moon', 'Lannister', '2024-11-01', '2025-01-01', '2024-11-01'),
    ('Fortune Telling with Finances', 'Let our financial seers guide you to a prosperous future. Your financial fortune awaits!', '299 AC, 20th Moon', 'Targaryen', '2024-11-01', '2025-01-01', '2024-11-01'),
    ('House of Savings', 'Join the House of Savings! Every coin saved is a step towards a secure future.', '299 AC, 22nd Moon', 'Stark', '2024-11-01', '2025-01-01', '2024-11-01'),
    ('The Art of War in Finance', 'Learn strategies to win the financial war! Knowledge is your greatest weapon.', '299 AC, 24th Moon', 'Baratheon', '2024-11-01', '2025-01-01', '2024-11-01'),
    ('Goldsmiths and Currency Experts', 'Our goldsmiths will guide you through currency exchange and investment strategies. Every coin matters!', '299 AC, 26th Moon', 'Lannister', '2024-11-01', '2025-01-01', '2024-11-01'),
    ('Financing Your Journey', 'Planning a journey? Let us help you finance your adventures. Every journey begins with a single coin!', '299 AC, 28th Moon', 'Stark', '2024-11-01', '2025-01-01', '2024-11-01'),
    ('Wealth Beyond the Wall', 'Our financial services are designed for those living beyond the Wall. Because everyone deserves to thrive!', '299 AC, 30th Moon', 'Other', '2024-11-01', '2025-01-01', '2024-11-01'),
    ('Mastering the Art of Currency', 'Join our workshops to master the art of currency management. Be the master of your own gold!', '299 AC, 32nd Moon', 'Targaryen', '2024-11-01', '2025-01-01', '2024-11-01'),
    ('A Lasting Legacy', 'Create a financial legacy that lasts for generations! Start your estate planning today.', '299 AC, 34th Moon', 'Baratheon', '2024-11-01', '2025-01-01', '2024-11-01');


