package com.winterfell.enums;

public enum LoanType {
    IRON_BANK_LOAN,
    WILDFIRE_PRODUCTION,
    DRAGON_EGG_ACQUISITION,
    WINTERFELL_RECONSTRUCTION,
    RAVEN_MESSAGE_SERVICE,
    VALYRIAN_STEEL_SMITHING,
    THE_WALL_DEFENSE_FUND,
    WHITE_WALKER_RESEARCH,
    HOUSE_BANNERS_PRODUCTION,
    KNIGHTHOOD_UPGRADE,
    MAESTER_TRAINING_FUND,
    TOURNEY_SPONSORSHIP,
    DOTHRAKI_HORSE_TRADE,
    ESSOS_TRADING_EXPEDITION,
    KINGSLANDING_REDEVELOPMENT
}

