import type { Metadata } from "next";
import "./globals.css";
import { Cinzel } from "next/font/google";
import Header from "./components/header";
import Footer from "./components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const cinzel = Cinzel({ weight: ['400', '900'], subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cinzel.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
